### ISSUE TITLE
PulseAudio handle return []

### ISSUE THREAD

**Issue by SeppBender** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#124]
I am trying to connect a mobile phone via bluetooth to my rasp 3B running stretch. I am getting a bluetooth connection but no audio stream is transmitted. 
In /var/log/messages is my device listed and the virtual device is created. But the output of 
[bluez-udev] PulseAudio module-loopback returned handle [] 

Does somebody know how to proceed? 

Thanks

**Comment by SeppBender** [comment]
I tried another phone and this one connects flawlessly via bluetooth and seams to stream data. Unfortunately I can't hear anything. I think it has something to with my setup because I wanted to use the internal audio card.

**Comment by BaReinhard** [comment]
Glad connection is working properly. You may want to take a look at soundcard configuration files (its been a while I can't remember the path to the file 😨 )



Future Reader:
Hey Guys, thanks for the interest in the project. Unfortunately, due to time constraints I am unable to address current issues and debugging, maintenance on the shell scripts are hard and inefficient. As such I will be porting over these scripts to ansible playbooks. This will allow for easier choosing of what you want installed, less brittle code base, and better maintenance so that less people experience the errors.

Once I have feature parity I will be addressing documentation on installing with ansible. The goal here is to allow people to setup multiple devices at once by only issuing one command, additionally to allow multiple OS support with less debugging and maintenance, as well as allowing other developers more easily add functionality to this repo with simple yaml files as opposed to obfuscated shell scripts.

Any open issues I will keep open to allow other community members to help solve issues, but currently I don't have the time to do so. I apologize for the lack of support, but once feature parity with ansible is achieved I believe everyone will be happier and better off.
Thanks for understanding.

![bitmoji](https://render.bitstrips.com/v2/cpanel/27c34645-4e03-42a5-bb21-c48c76fcacfe-15cd827c-4baa-4b09-a22d-0d657c319951-v1.png?transparent=1&palette=1&width=246)
