### ISSUE TITLE
No audio from Volumio, after connecting phone via bluetooth

### ISSUE THREAD

**Issue by wodgey** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#132]
2nd edit to add--- working! awesome. Thanks for your work.
(changed a setting from 0 to 1. "audio_sink" I think

Really unhelpful post, this one. I think it is alsmost defiitely the issue where I need to do something with the sink settings.
HOWEVER, we have a poorly patient sleeping in the same room as the pi/hi-fi. so it will have to wait.

There was an error when running the script where it failed on bt-pa-config.sh (can;t remember the name) but I rebooted, and re-ran the script again directy and it completed. 

This "issue" isn;t a request for help, more of a "thanks for all your work" post. 

I've also just written an SD card with the latest volumio image so I can try out the bluez-alsa work from this github https://github.com/Arkq/bluez-alsa (this appeals to the OCD purist in me, whereas your work appeals to the *nix newbie in me, due to its simplicity) edit2add. I think I;ve been a numpty and linbked the wrong github. I suspect this is for sendiing audio to a BT speaker

Oh, I forgot to add that your script seemd to hang at "upgrading via apt-get" and stayed there for 24 hours. I rebooted and ran dpkg -a --configure and it seems due to dhcpd update needing user input for the "keep old settings/write new settings" dialogue. WHen I try this again on a clean install, I'll remember to aptget update &&aptget upgrade beforehand.

Fell free to close the psot/flame me for being unhelpful and clogging up the issues board. I just didn;t know where the forums are to thank you there

Digital Kit :- 
RasPi 2 Model B(+?)
Allo reclocker (for the life of me I cannot bring its name to mind. Keep thinking "Kodi" which I know is incorreect)

Mamboberry LS DAC+

Analogue stuff :- 
Yamaha NS200 Floorstanders
Nad C320 amp

**Comment by BaReinhard** [comment]
glad you got things working!!!


Message for future people reading this issue:
Hey Guys, thanks for the interest in the project. Unfortunately, due to time constraints I am unable to address current issues and debugging, maintenance on the shell scripts are hard and inefficient. As such I will be porting over these scripts to ansible playbooks. This will allow for easier choosing of what you want installed, less brittle code base, and better maintenance so that less people experience the errors.

Once I have feature parity I will be addressing documentation on installing with ansible. The goal here is to allow people to setup multiple devices at once by only issuing one command, additionally to allow multiple OS support with less debugging and maintenance, as well as allowing other developers more easily add functionality to this repo with simple yaml files as opposed to obfuscated shell scripts.

Any open issues I will keep open to allow other community members to help solve issues, but currently I don't have the time to do so. I apologize for the lack of support, but once feature parity with ansible is achieved I believe everyone will be happier and better off.
Thanks for understanding.

![bitmoji](https://render.bitstrips.com/v2/cpanel/27c34645-4e03-42a5-bb21-c48c76fcacfe-15cd827c-4baa-4b09-a22d-0d657c319951-v1.png?transparent=1&palette=1&width=246)
