### ISSUE TITLE
Bug in airplay_config.sh?

### ISSUE THREAD

**Issue by TKlasema** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#21]
Hi!
In line 69 and 70 the path for the start/end scripts _shairportstart.sh_ and _shairportend.sh_ is "_usr/local/bin_" but in line 217..220 these scripts are copied to "_/home/pi/shScripts/_". Isn't this a mismatch?
Also, I copied them to "_usr/local/bin_" but it seems they're not executed. 

Background: the volume level for Bluetooth is much higher than for AirPlay and I see that _amixer_ gives me only 80% of the Master Level. So I wanted to increase this in _shairportstart.sh_ to 100% by adding _sudo amixer set Master 100%_, but without success.

Could you please verify that?
Thanks a lot and regards

**Comment by BaReinhard** [comment]
That was old remnants from the old setup. Change that to the proper location `/usr/local/bin`

Within the scripts don't use sudo as the scripts will be run as root anyway since shairport-sync is run as a system daemon. So every service/script it runs will also be root. It is also recommended that things like `amixer ` are run as absolute paths I.e. `/usr/bin/amixer` or `/bin/amixer `wherever it is actually located
