### ISSUE TITLE
kodi issues along with no BT and Airplay

### ISSUE THREAD

**Issue by HiteshBaadkar** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#31]
Audio plays fine(using allstream app) but no airplay or bt
kodi plays the audio perfectly but crashes when trying to launch it as a GUI, launched from the pi itself under sound and video with this error appearing the terminal:

pi@Cosmic_Hawk:~ $ sudo systemctl status kodi
● kodi.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

pi@Cosmic_Hawk:~ $ *** Error in `/usr/lib/arm-linux-gnueabihf/kodi/kodi_v7.bin': free(): invalid pointer: 0x02b886b4 ***

**Comment by BaReinhard** [comment]
I am unfamiliar with allstream.

I would need some more information on what installation you chose.

From what I recall is that kodi is not managed by `systemctl` and has its own file in the home directory for your current user. In this folder is where you set how it runs, it has been a while since I played with it.

So there is no audio that plays when you play from AirPlay or from Bluetooth?
